name: Install repository with compilation cache

runs:
  using: composite

  steps:
    - uses: ./.github/actions/install

    - name: Restore forge compilation cache
      uses: actions/cache/restore@v3
      with:
        path: |
          cache
          out
        key: forge-${{ github.ref_name }}
        restore-keys: |
          forge-${{ github.base_ref }}
          forge-
