name: Foundry

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Compilation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1

      - name: Build contracts & check sizes
        run: forge build --force --sizes # don't use compilation cache

  test:
    needs: build

    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        type: ["slow", "fast"]
        include:
          - type: "slow"
            fuzz-runs: 1024
            max-test-rejects: 1048576
            invariant-runs: 32
            invariant-depth: 512
          - type: "fast"
            fuzz-runs: 256
            max-test-rejects: 65536
            invariant-runs: 16
            invariant-depth: 256

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive

      - name: Build morpho-blue
        run: cd lib/morpho-blue && forge build

      - name: Run tests in ${{ matrix.type }} mode
        run: forge test -vvv
        env:
          FOUNDRY_FUZZ_RUNS: ${{ matrix.fuzz-runs }}
          FOUNDRY_FUZZ_MAX_TEST_REJECTS: ${{ matrix.max-test-rejects }}
          FOUNDRY_INVARIANT_RUNS: ${{ matrix.invariant-runs }}
          FOUNDRY_INVARIANT_DEPTH: ${{ matrix.invariant-depth }}
          FOUNDRY_FUZZ_SEED: 0x${{ github.event.pull_request.base.sha || github.sha }}
