name: Hardhat

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build-contracts:
    name: Gas tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/install

      - name: Build contracts
        run: yarn build:hardhat --force # don't use compilation cache

      - name: Run hardhat tests
        run: yarn test:hardhat
